apiVersion: v1
kind: Service
metadata:
  name: cns-catalog-service
  labels:
    app: cns-catalog-service
spec:
  type: ClusterIP
  selector:
    app: cns-catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001

