version: '3'
services:
  cns-catalog-service:
    depends_on:
      - cns-catalog-service-db
    image: cns-catalog-service
    container_name: cns-catalog-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cns-catalog-service-db:5432/cns-catalog
    ports:
      - "9001:9001"
    networks:
      - catalog-network
  cns-catalog-service-db:
    image: postgres:13.3
    container_name: cns-catalog-service-db
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cns-catalog
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge
